### ISSUE TITLE
Upgrade to ginkgo v2

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/blackbox#31]

**Comment by ctlong** [comment]
Found that this is impossible to accomplish at present, as it results in a panic within the integration tests:
```
$ go run github.com/onsi/ginkgo/v2/ginkgo -r
blackbox/integration/integration.test flag redefined: ginkgo.seed
panic: blackbox/integration/integration.test flag redefined: ginkgo.seed

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc000116120, {0x1528530, 0x17a4020}, {0xc00002f6b0, 0xb}, {0x147a453, 0x2a})
	/usr/local/Cellar/go/1.19.2/libexec/src/flag/flag.go:980 +0x2f9
flag.(*FlagSet).Int64Var(...)
	/usr/local/Cellar/go/1.19.2/libexec/src/flag/flag.go:767
github.com/onsi/ginkgo/config.Flags(0x1?, {0x146270c?, 0x139380f?}, 0x1)
	blackbox/vendor/github.com/onsi/ginkgo/config/config.go:75 +0xf1
github.com/onsi/ginkgo.init.0()
	blackbox/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:53 +0x35

Ginkgo ran 1 suite in 1.03331765s

Test Suite Failed
exit status 1
```
